# Generated by Django 4.0.3 on 2022-05-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('move1', models.CharField(max_length=100)),
                ('move2', models.CharField(max_length=100)),
                ('move3', models.CharField(max_length=100)),
                ('srcImg', models.CharField(max_length=300)),
                ('favorite', models.BooleanField(default=False)),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon.user')),
            ],
        ),
    ]
